language: python

python:
  - "2.7"
  - "3.5"

os:
  - linux

# command to install dependencies
install:
  - pip install -q -U pip setuptools nose coveralls
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy

# command to run tests
script:
  - nosetests --with-coverage --cover-package=amadeus
